networks:
    app_network:
        name: app_network
        driver: bridge

services:
    backend:
        image: rahulcodepython/password-manager-backend

        container_name: password-manager-backend-app

        restart: unless-stopped

        volumes:
            - staticfiles:/app/staticfiles

        networks:
            - app_network

    frontend:
        image: rahulcodepython/password-manager-frontend

        container_name: password-manager-frontend-app

        restart: unless-stopped

        networks:
            - app_network

        depends_on:
            - backend

    nginx:
        image: rahulcodepython/password-manager-nginx

        container_name: password-manager-nginx-app

        ports:
            - 80:80

        networks:
            - app_network

        restart: unless-stopped

        volumes:
            - staticfiles:/app/static

        depends_on:
            - backend
            - frontend

volumes:
    staticfiles:
