networks:
    app_network:
        driver: bridge

services:
    postgresdb:
        image: postgres

        restart: unless-stopped

        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=rahul
            - POSTGRES_PASSWORD=admin

        volumes:
            - ./data/postgresdb:/var/lib/postgresql/data

        networks:
            - app_network

    backend:
        image: rahulcodepython/coursehunt-backend:latest

        container_name: courseHunt-backend-app

        restart: unless-stopped

        volumes:
            - staticfiles:/app/static

        depends_on:
            - postgresdb

        networks:
            - app_network

    frontend:
        image: rahulcodepython/coursehunt-frontend:latest

        container_name: courseHunt-frontend-app

        restart: unless-stopped

        networks:
            - app_network

    nginx:
        image: rahulcodepython/coursehunt-nginx:latest

        container_name: coursehunt-nginx-app

        restart: unless-stopped

        ports:
            - 80:80

        networks:
            - app_network

        volumes:
            - staticfiles:/app/static

        depends_on:
            - backend
            - frontend

volumes:
    staticfiles:
