networks:
    app_network:
        driver: bridge

services:
    db:
        image: postgres

        container_name: libom-db-app

        restart: unless-stopped

        volumes:
            - ./data:/var/lib/postgresql/data

        # ports:
        #     - "5432:5432" # Ensure no other service is running on this port

        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=rahul
            - POSTGRES_PASSWORD=admin

        networks:
            - app_network

    backend:
        image: rahulcodepython/libom-backend

        container_name: libom-backend-app

        restart: unless-stopped

        volumes:
            - staticfiles:/app/static

        depends_on:
            - db

        networks:
            - app_network

    frontend:
        image: rahulcodepython/libom-frontend

        container_name: libom-frontend-app

        restart: unless-stopped

        networks:
            - app_network

    nginx:
        image: rahulcodepython/libom-nginx

        container_name: libom-nginx-app

        restart: unless-stopped

        ports:
            - 80:80

        networks:
            - app_network

        volumes:
            - staticfiles:/app/static

        depends_on:
            - backend
            - frontend

volumes:
    staticfiles:
